# Generated by Django 5.0.1 on 2024-02-02 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_usuario_alter_empresa_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
    ]
